"""Authoritative information artifact models for Phase 5 data provenance."""

from datetime import UTC, datetime
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field

from app.schemas.enums import ArtifactSourceType, DataClassification, ProvenanceTrust, TrustLevel


class InformationArtifact(BaseModel):
    """Authoritative, deeply immutable security representation of an information object.

    Enforces:
    - Server-generated immutable UUID (artifact_id).
    - Deep immutability using frozensets and tuples with frozen=True, extra="forbid".
    - Provenance tracking without storing raw payloads in metadata or causal graphs.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    artifact_id: UUID = Field(
        default_factory=uuid4, description="Server-authoritative unique artifact UUID"
    )
    session_id: str = Field(
        ..., description="CAGE session to which this artifact is strictly bound"
    )
    created_by_action_id: UUID | None = Field(
        default=None, description="Authoritative producing action ID (if generated by a tool)"
    )
    source_type: ArtifactSourceType = Field(..., description="High-level origin category")
    source_resource: str = Field(..., description="Normalized resource or tool identifier")
    direct_trust_level: ProvenanceTrust | TrustLevel = Field(
        ..., description="Direct trust level of immediate source"
    )
    inherited_trust_levels: frozenset[ProvenanceTrust | TrustLevel] = Field(
        default_factory=frozenset,
        description="Monotonic accumulation of parent trust levels (anti-laundering)",
    )
    data_classifications: frozenset[DataClassification] = Field(
        default_factory=frozenset,
        description="Union of server-known and parent sensitivity classifications",
    )
    parent_artifact_ids: tuple[UUID, ...] = Field(
        default_factory=tuple,
        description="Immediate parent artifact IDs from which this artifact was derived",
    )
    content_digest: str | None = Field(
        default=None, description="SHA-256 hex digest for correlation and integrity evidence"
    )
    size_bytes: int | None = Field(default=None, description="Payload byte size")
    mime_type: str | None = Field(default=None, description="MIME content type")
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="Server timestamp when artifact was registered",
    )


class ArtifactCreationSpec(BaseModel):
    """Internal server-side specification for creating an InformationArtifact.

    Clients NEVER submit artifact_id, trust, classification, or lineage directly.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    session_id: str
    created_by_action_id: UUID | None = None
    source_type: ArtifactSourceType
    source_resource: str
    direct_trust_level: TrustLevel
    inherited_trust_levels: frozenset[TrustLevel] = Field(default_factory=frozenset)
    data_classifications: frozenset[DataClassification] = Field(default_factory=frozenset)
    parent_artifact_ids: tuple[UUID, ...] = Field(default_factory=tuple)
    content_digest: str | None = None
    size_bytes: int | None = None
    mime_type: str | None = None
